name = "cr-worker"
main = ".mastra/output/index.mjs"
compatibility_date = "2024-12-02"
compatibility_flags = ["nodejs_compat", "enable_top_level_await_in_require"]


[vars]
OPENAI_API_KEY = ""
SCOPE=""
CLOUDFLARE_API_TOKEN=""
CLOUDFLARE_EMAIL=""

[env.production]
compatibility_date = "2024-12-02"
compatibility_flags = ["nodejs_compat"]