name = "agent-worker"
main = ".mastra/output/index.mjs"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]


[vars]
OPENAI_API_KEY = ""
SCOPE=""

[env.production]
compatibility_date = "2024-12-02"
compatibility_flags = ["nodejs_compat"]